version: '2'

services:
  axon-server:
    image: axoniq/axonserver:latest
    ports:
      - '8024:8024'
      - '8124:8124'
  mongodb:
    image: mongo:latest 
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/data/db'
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer:latest
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  mongodb_data:
    driver: local
  mysql_data:
    driver: local
